/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.race.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Race service. Represents a row in the &quot;RACE_Race&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.example.race.model.impl.RaceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.example.race.model.impl.RaceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Race
 * @generated
 */
@ProviderType
public interface RaceModel
	extends BaseModel<Race>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a race model instance should use the {@link Race} interface instead.
	 */

	/**
	 * Returns the primary key of this race.
	 *
	 * @return the primary key of this race
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this race.
	 *
	 * @param primaryKey the primary key of this race
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this race.
	 *
	 * @return the uuid of this race
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this race.
	 *
	 * @param uuid the uuid of this race
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the race ID of this race.
	 *
	 * @return the race ID of this race
	 */
	public long getRaceId();

	/**
	 * Sets the race ID of this race.
	 *
	 * @param raceId the race ID of this race
	 */
	public void setRaceId(long raceId);

	/**
	 * Returns the group ID of this race.
	 *
	 * @return the group ID of this race
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this race.
	 *
	 * @param groupId the group ID of this race
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this race.
	 *
	 * @return the company ID of this race
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this race.
	 *
	 * @param companyId the company ID of this race
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this race.
	 *
	 * @return the user ID of this race
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this race.
	 *
	 * @param userId the user ID of this race
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this race.
	 *
	 * @return the user uuid of this race
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this race.
	 *
	 * @param userUuid the user uuid of this race
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this race.
	 *
	 * @return the user name of this race
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this race.
	 *
	 * @param userName the user name of this race
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this race.
	 *
	 * @return the create date of this race
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this race.
	 *
	 * @param createDate the create date of this race
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this race.
	 *
	 * @return the modified date of this race
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this race.
	 *
	 * @param modifiedDate the modified date of this race
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this race.
	 *
	 * @return the name of this race
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this race.
	 *
	 * @param name the name of this race
	 */
	public void setName(String name);

	/**
	 * Returns the description of this race.
	 *
	 * @return the description of this race
	 */
	public boolean getDescription();

	/**
	 * Returns <code>true</code> if this race is description.
	 *
	 * @return <code>true</code> if this race is description; <code>false</code> otherwise
	 */
	public boolean isDescription();

	/**
	 * Sets whether this race is description.
	 *
	 * @param description the description of this race
	 */
	public void setDescription(boolean description);

	@Override
	public Race cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}