/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.example.race.model.impl;

import com.example.race.model.Race;
import com.example.race.service.RaceLocalServiceUtil;

/**
 * The extended model base implementation for the Race service. Represents a row in the &quot;RACE_Race&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RaceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RaceImpl
 * @see Race
 * @generated
 */
public abstract class RaceBaseImpl extends RaceModelImpl implements Race {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a race model instance should use the <code>Race</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RaceLocalServiceUtil.addRace(this);
		}
		else {
			RaceLocalServiceUtil.updateRace(this);
		}
	}

}